### ISSUE TITLE
`inet_addr` no longer exists

### ISSUE THREAD

**Issue by endgame** [swift-nav/preamble#7]
`preamble` fails to build with `network >= 3.0.0.0`, which was the version which removed the deprecated `inet_addr` function:

```
preamble                > /run/user/1000/stack-9cb33ad2357a5e3f/preamble-0.0.65/src/Preamble/Ctx.hs:49:17: error:
preamble                >     Variable not in scope: inet_addr :: [Char] -> IO HostAddress
preamble                >    |
preamble                > 49 |   a <- liftIO $ inet_addr h
preamble                >    |                 ^^^^^^^^^
```

**Comment by gborough** [comment]
This problem is also observed when building wolf:

preamble             > [11 of 12] Compiling Preamble.Ctx
preamble             >
preamble             > /private/var/folders/hp/p1d75b2s5h5f83wyt65vkd2r0000gn/T/stack-8a2a9669ce686ab5/preamble-0.0.61/src/Preamble/Ctx.hs:49:17: error:
preamble             >     Variable not in scope: inet_addr :: [Char] -> IO HostAddress
preamble             >    |
preamble             > 49 |   a <- liftIO $ inet_addr h
preamble             >    |                 ^^^^^^^^^
preamble             >
